### ISSUE TITLE
볼륨 컨트롤 이벤트 시 적절한 마우스 제스쳐

### ISSUE THREAD

**Issue by likedemian** [dlqjaen/WeatherSound#25]
mousemove 이벤트가 적절하나, 볼륨 버튼 위에서 드래그 하지 않고 스치기만 해도 이벤트가 실행되는 문제 발생.

적절한 drag 이벤트를 찾지못함. ㅠ_ㅠ

**Comment by dlqjaen** [comment]
마우스 이벤트 에서 마우스무브를 사용해도 되지만 마우스 업 이벤트를 사용 하는게 더 나은 방법
